### ISSUE TITLE
extaddr and shortaddr not reset in cache with MLME_reset

### ISSUE THREAD

**Issue by CiaranWoodward** [Cascoda/ca821x-api#5]
```pDeviceRef->shortaddr``` and ```pDeviceRef->extaddr``` should mirror what is in the pib, so should be reset to default values with MLME_reset

**Comment by CiaranWoodward** [comment]
Unsure if extaddr is actually reset on pib, so might just be the shortaddr

**Comment by HarryMorris** [comment]
extaddr is indeed not touched by MLME-RESET

**Comment by HarryMorris** [comment]
fixed in 5eea96825c4995790e8542405ffcc03db171925f
